"""
S&P 100 構成銘柄リスト（時価総額上位100社相当）
バックテスト用 --universe sp100 で使用
"""

SP100_TICKERS = [
    ("AAPL",  "Apple"),
    ("MSFT",  "Microsoft"),
    ("NVDA",  "NVIDIA"),
    ("AMZN",  "Amazon"),
    ("GOOGL", "Alphabet (A)"),
    ("GOOG",  "Alphabet (C)"),
    ("META",  "Meta Platforms"),
    ("TSLA",  "Tesla"),
    ("AVGO",  "Broadcom"),
    ("BRK.B", "Berkshire Hathaway"),
    ("JPM",   "JPMorgan Chase"),
    ("LLY",   "Eli Lilly"),
    ("XOM",   "Exxon Mobil"),
    ("WMT",   "Walmart"),
    ("V",     "Visa"),
    ("MA",    "Mastercard"),
    ("COST",  "Costco"),
    ("ORCL",  "Oracle"),
    ("NFLX",  "Netflix"),
    ("JNJ",   "Johnson & Johnson"),
    ("UNH",   "UnitedHealth Group"),
    ("HD",    "Home Depot"),
    ("PG",    "Procter & Gamble"),
    ("ABBV",  "AbbVie"),
    ("BAC",   "Bank of America"),
    ("CVX",   "Chevron"),
    ("AMD",   "AMD"),
    ("KO",    "Coca-Cola"),
    ("CSCO",  "Cisco Systems"),
    ("GS",    "Goldman Sachs"),
    ("MS",    "Morgan Stanley"),
    ("PM",    "Philip Morris"),
    ("CRM",   "Salesforce"),
    ("MRK",   "Merck"),
    ("WFC",   "Wells Fargo"),
    ("IBM",   "IBM"),
    ("CAT",   "Caterpillar"),
    ("GE",    "GE Aerospace"),
    ("AMAT",  "Applied Materials"),
    ("LRCX",  "Lam Research"),
    ("RTX",   "RTX"),
    ("LIN",   "Linde"),
    ("NOW",   "ServiceNow"),
    ("TXN",   "Texas Instruments"),
    ("ISRG",  "Intuitive Surgical"),
    ("BKNG",  "Booking Holdings"),
    ("QCOM",  "Qualcomm"),
    ("BLK",   "BlackRock"),
    ("PEP",   "PepsiCo"),
    ("VZ",    "Verizon"),
    ("T",     "AT&T"),
    ("AXP",   "American Express"),
    ("DIS",   "Walt Disney"),
    ("MCD",   "McDonald's"),
    ("AMGN",  "Amgen"),
    ("TMO",   "Thermo Fisher"),
    ("NEE",   "NextEra Energy"),
    ("ABT",   "Abbott Laboratories"),
    ("TMUS",  "T-Mobile US"),
    ("TJX",   "TJX Companies"),
    ("INTU",  "Intuit"),
    ("COP",   "ConocoPhillips"),
    ("ACN",   "Accenture"),
    ("LOW",   "Lowe's"),
    ("SPGI",  "S&P Global"),
    ("PANW",  "Palo Alto Networks"),
    ("C",     "Citigroup"),
    ("GILD",  "Gilead Sciences"),
    ("PLD",   "Prologis"),
    ("SYK",   "Stryker"),
    ("ADI",   "Analog Devices"),
    ("HON",   "Honeywell"),
    ("VRTX",  "Vertex Pharmaceuticals"),
    ("ETN",   "Eaton Corporation"),
    ("BMY",   "Bristol-Myers Squibb"),
    ("LMT",   "Lockheed Martin"),
    ("UBER",  "Uber Technologies"),
    ("PFE",   "Pfizer"),
    ("CB",    "Chubb"),
    ("DE",    "Deere & Company"),
    ("UNP",   "Union Pacific"),
    ("SCHW",  "Charles Schwab"),
    ("PGR",   "Progressive"),
    ("CME",   "CME Group"),
    ("MDT",   "Medtronic"),
    ("MO",    "Altria Group"),
    ("CI",    "Cigna"),
    ("SO",    "Southern Company"),
    ("DUK",   "Duke Energy"),
    ("MMC",   "Marsh McLennan"),
    ("APD",   "Air Products"),
    ("PH",    "Parker-Hannifin"),
    ("ITW",   "Illinois Tool Works"),
    ("HCA",   "HCA Healthcare"),
    ("REGN",  "Regeneron"),
    ("USB",   "US Bancorp"),
    ("NOC",   "Northrop Grumman"),
    ("COF",   "Capital One"),
    ("TGT",   "Target"),
    ("SBUX",  "Starbucks"),
    ("NKE",   "Nike"),
]


def get_sp100_tickers() -> list[str]:
    return [t for t, _ in SP100_TICKERS]
